todolists/config/routes.rb
Rails.application.routes.draw do

  root to: "todo_lists#index"

  resources :todo_lists do
    resources :todo_items
  end
  
  resources :sessions, only: [:new, :create, :destroy] 

  get "/login" => "sessions#new", as: "login"

  delete "/logout" => "sessions#destroy", as: "logout"

end

todolists/app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  belongs_to :todo_list
  # Add a default scope to always return collections from the database ordered by due dates with earliest dates first. 
  default_scope {order :due_date}
end

todolists/app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  
  # Add a private helper method called set_todo_list that sets the todo_list instance variable from the :todo_list_id property passed in via the params. 
  before_action :set_todo_list

  before_action :set_todo_item, only: [:show, :edit, :update, :destroy]


  # GET /todo_items/1
  # GET /todo_items/1.json
  def show
  end

  # GET /todo_items/new
  # Update the todo_item#new action to return a new TodoItem instance that is initialized to reference its parent @todo_list, which is provided by set_todo_list.
  def new
    @todo_item = @todo_list.todo_items.new
  end

  # GET /todo_items/1/edit
  def edit
  end

  # POST /todo_items
  # POST /todo_items.json

  # Update the todo_item#create to create a new TodoItem instance based on the todo_item_params as before. Except now create this instance associated with the @todo_list provided by set_todo_list.
  def create
    @todo_item = @todo_list.todo_items.new(todo_item_params)

    respond_to do |format|
      if @todo_item.save
        format.html { redirect_to @todo_list, notice: 'Todo item was successfully created.' }
        format.json { render :show, status: :created, location: @todo_item }
      else
        format.html { render :new }
        format.json { render json: @todo_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_items/1
  # PATCH/PUT /todo_items/1.json
  def update
    respond_to do |format|
      if @todo_item.update(todo_item_params)
        format.html { redirect_to @todo_list, notice: 'Todo item was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_item }
      else
        format.html { render :edit }
        format.json { render json: @todo_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_items/1
  # DELETE /todo_items/1.json
  def destroy
    @todo_item.destroy
    respond_to do |format|
      format.html { redirect_to @todo_list, notice: 'Todo item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions. Update the private helper method called set_todo_item to scope its find command to the todo_items of a specific @todo_list list.
    def set_todo_item
      @todo_item = @todo_list.todo_items.find(params[:id])
    end

    def set_todo_list
      @todo_list = TodoList.find(params[:todo_list_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_item_params
      params.require(:todo_item).permit(:title, :due_date, :description, :completed)
    end
end

todolists/app/helpers/to_do_items_helper.rb
module ToDoItemsHelper
end

todolists/app/views/todo_items/_form.html.erb
<%= form_for([@todo_list, @todo_item]) do |f| %>
  <% if @todo_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_item.errors.count, "error") %> prohibited this todo_item from being saved:</h2>

      <ul>
      <% @todo_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :due_date %><br>
    <%= f.date_select :due_date %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
 <!--  Make the display of completed conditional on the todo_item being edited versus new. Users should not be allowed to see/change the completed property for a new TodoItem. Edited objects are persisted and can be tested using persisted?. . -->
  <% if @todo_item.persisted? %>
  <div class="field">
    <%= f.label :completed %><br>
    <%= f.check_box :completed %>
  </div>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

todolists/app/views/todo_items/edit.html.erb
<h1>Editing Todo Item</h1>

<%= render 'form' %>

<%= link_to 'Show', [@todo_list, @todo_item] %> |
<%= link_to 'Back', @todo_list %>

todolists/app/views/todo_items/new.html.erb
<h1>New Todo Item</h1>

<%= render 'form' %>

<%= link_to 'Back', @todo_list %>

todolists/app/views/todo_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @todo_item.title %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @todo_item.due_date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @todo_item.description %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @todo_item.completed %>
</p>

<!-- Update the links on the todo_items#show page (todo_items/show.html.erb) to include the TodoList the TodoItem is a member of. -->
<%= link_to 'Edit', edit_todo_list_todo_item_path(@todo_list, @todo_item) %> |
<%= link_to 'Back', @todo_list %>